Upload only support
nimbis/s3commander pull request #35
Opened 2019-04-04 23:02 UTC by mliudev

Add a flag to limit download capability.

2019-04-04 23:02 UTC, mliudev commented
![](https://github.trello.services/images/mini-trello-icon.png) [Modify S3Commander to use a flag to toggle download access.](https://trello.com/c/a3EljO0C/6-modify-s3commander-to-use-a-flag-to-toggle-download-access)

2019-04-05 14:35 UTC, CtrlC-Root requested changes
Please modify the HTML template to expose `allow-download` as a checkbox. This makes testing easier and demos the feature to someone looking at the sample. Otherwise code looks good.

2019-04-05 19:03 UTC, mliudev commented
@CtrlC-Root I've added the requested checkbox toggle. Ready for re-review.

2019-04-05 22:25 UTC, CtrlC-Root approved these changes

2019-04-06 00:27 UTC, merged